
DATABASE: "sqlite"                                                                                          # only sqlite avaible for now (next versions may have mysql option)

DEFAULT_Gold: 100.00                                                                                        # default gold user get on first join
DEFAULT_Silver : 50.00                                                                                      # default silver user get on first join

VALUE_OF_1_GOLD_IN_SILVER: 100                                                                              # used in baltop and in the excange (if enabled)

EXCHANGE_CURRENCYES: 1                                                                                      # if 0 command /exchange is disabled

DEFAULT_VAULT_I_NTERACTION: "SILVER"                                                                        # vault is not created to support >1 currencyes, in order to connect with others
                                                                                                            # plugin I suggest to use "SILVER" (u can use "GOLD" too) and enable exchange


